site_name: Administração de TI - Documentação
nav:
  - Home: index.md
  - Sobre: about.md
  - Introdução: introduction.md
  - GLPI: glpi.md
  - MkDocs: mkdocs.md
  - Conclusão: conclusion.md
theme:
    name: simple-blog
plugins:
  - search
  - mkdocstrings
  