site_name: Administração de TI - Documentação
nav:
  - Home: index.md
  - Sobre: about.md
  - Introdução: introduction.md
  - GLPI: glpi.md
  - MkDocs: mkdocs.md
  - Conclusão: conclusion.md
theme:
    name: simple-blog
    # logo: assets/logo.ico
    # favicon: assets/logo.ico
plugins:
  - search
  - mkdocstrings
  